/// Flutter icons MDIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
//
///
///
import 'package:flutter/widgets.dart';

class MdIcons {
  MdIcons._();

  static const _kFontFam = 'MDIcons';

  // ignore_for_file: constant_identifier_names
  static const IconData kidneys =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData pediatrician_o =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData dentist =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData surgeon_o =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData surgeon =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pediatrician =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData prostate_o =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData prostate =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData runny_nose_o =
      IconData(0xe809, fontFamily: _kFontFam);
  static const IconData kidneys_o =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData skin_o =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData runny_nose =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData eye =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData eye_o =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData stethoscope =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData skin =
      IconData(0xe810, fontFamily: _kFontFam);
}
