/// Generated by AssetsRefGenerator on 2020/10/08
class Res {
  static const String music = "assets/img/music.gif";
  static const String music_two = "assets/img/music_two.png";
  static const String movie = "assets/img/movie.gif";
  static const String findout = "assets/img/findout.png";
  static const String medical_appointment = "assets/img/medical_appointment.png";
  static const String photographers_app = "assets/img/photographers_app.png";
  static const String instagram = "assets/img/ig.png";
}

